<?php
return [
    'breakdown_col' => [
        'cat',
        'type',
        'kode',
        'tpk',
        'no',
        'nama_modul',
        'component',
        'proses_khusus',
        'P',
        'L',
        'T',
        'ukuran',
        'sub',
        'jml',
        'bahan',
        't_bahan',
        'l_bahan',
        'd_bahan',
        'luar',
        't_luar',
        'dalam',
        't_dalam',
        'p1',
        'p2',
        'l1',
        'l2',
        'p1_bahan',
        'p2_bahan',
        'l1_bahan',
        'l2_bahan',
        'profile3',
        'profile2',
        'profile',
        'siku_joint',
        'screw_jf',
        'door_mec',
        'rel',
        'engsel',
        'v',
        'v2',
        'h',
        'nama_barang',
        'panjang',
        'jumlah',
        'v_lap',
        'v_edg',
        'deskripsi_lapisan',
        'deskripsi_edging',
        'deskripsi_komponen',
        'nama_komponen',
        'minifix',
        'dowel',
        '@siku',
        '@screw',
        'dormec',
        'engsel',
        'rel',
        'p',
        'l',
        '2(p+l)',
        '(pxl)',
        'bahan_dasar',
        'deskripsi_bahan',
        '/panel',
        'jumlah_anodize@',
        'minifix@',
        'dowel@',
        'jml_siku',
        'jml_screw',
        'M2',
        'M3',
        'T_P1',
        'T_P2',
        'T_L1',
        'T_L2',
        'P_cnc',
        'ukuran_cnc',
        'csv_format',
    ],

    'fields_mapping' => [
        'cat' => 'cat',
        'code' => 'type',
        'KS' => 'kode',
        'tpk' => 'Tpk',
        'no' => 'No',
        'name' => 'component',
        'proses_khusus' => 'proses_khusus',
        'P' => 'P',
        'L' => 'L',
        'T' => 'T',
        'ukuran' => 'ukuran',
        'number_of_sub' => 'Sub',
        'jml' => 'jml',
        'material' => 'bahan',
        't_bahan' => 't_bahan',
        'outside' => 'l_bahan',
        'inside' => 'd_bahan',
        'luar' => 'luar',
        't_luar' => 't_luar',
        'dalam' => 'dalam',
        't_dalam' => 't_dalam',
        'p1' => 'p1',
        'p2' => 'p2',
        'l1' => 'l1',
        'l2' => 'l2',
        'p1_bahan' => 'p1_bahan',
        'p2_bahan' => 'p2_bahan',
        'l1_bahan' => 'l1_bahan',
        'l2_bahan' => 'l2_bahan',
        'profile3' => 'profile3',
        'profile2' => 'profile2',
        'profile' => 'profile',
        'siku_joint' => 'siku_joint',
        'screw_jf' =>  'screw_jf',
        'door_mec' => 'door_mec',
        'rel' => 'rel',
        'engsel' => 'engsel',
        'v' => 'v',
        'v2' => 'v2',
        'h' => 'h',
        'nama_barang' => 'nama_barang',
        'panjang' => 'panjang',
        'jumlah' => 'jumlah',
        'v_lap' => 'v_lap',
        'v_edg' => 'v_edg',
        'deskripsi_lapisan' => 'deskripsi_lapisan',
        'deskripsi_edging' => 'deskripsi_edging',
        'deskripsi_komponen' => 'deskripsi_komponen',
        'nama_komponen' => 'nama_komponen',
        'minifix' => 'minifix',
        'dowel' => 'dowel',
        '@siku' => '@siku',
        '@screw' => '@screw',
        'dormec' =>  'dormec',
        'p' => 'p',
        'l' =>  'l',
        '2(p+l)' => '2(p+l)',
        '(pxl)' => '(pxl)',
        'bahan_dasar' => 'bahan_dasar',
        'deskripsi_bahan' => 'deskripsi_bahan',
        '/panel' => '/panel',
        'jumlah_anodize@' => 'jumlah_anodize@',
        'minifix@' => 'minifix@',
        'dowel@' => 'dowel@',
        'jml_siku' => 'jml_siku',
        'jml_screw' => 'jml_screw',
        'M2' => 'M2',
        'M3' => 'M3',
        'T_P1' => 'T_P1',
        'T_P2' => 'T_P2',
        'T_L1' => 'T_L1',
        'T_L2' => 'T_L2',
        'P_cnc' =>  'P_cnc',
        'ukuran_cnc' => 'ukuran_cnc',
        'csv_format' => 'csv_format',
    ],

    'data_validation_col' => [
        'code',
        'name',
        'val',
        'ks',
        'ket',
        'jml sub',
        'bhn',
        'T',
        'minifix',
        'dowel',
        'tipe siku',
        'tipe screw',
        'V',
        'V2',
        'H',
        'profil3',
        'profil2',
        'profil',
        'L',
        'D',
        'P1',
        'P2',
        'L1',
        'L2',
        'Rel',
        'Engsel',
        'Anodize',
        'Jumlah anodize@',
        'P',
        'L',
        '@siku',
        '@screw'
    ],
    'data_val_map' => [
        'code' => 'code',
        'name' => 'name',
        'val' => 'val',
        'KS' => 'ks',
        'Ket' => 'ket',
        'number_of_sub' => 'jml sub',
        'material' => 'bhn',
        'thickness' => 'T',
        'minifix' => 'minifix',
        'dowel' => 'dowel',
        'elbow_type' => 'tipe siku',
        'screw_type' => 'tipe screw',
        'V' => 'V',
        'V2' => 'V2',
        'H' => 'H',
        'profile3' => 'profil3',
        'profile2' => 'profil2',
        'profile' => 'profil',
        'outside' => 'L',
        'inside' => 'D',
        'P1' => 'P1',
        'P2' => 'P2',
        'L1' => 'L1',
        'L2' => 'L2',
        'rail' => 'Rel',
        'hinge' => 'Engsel',
        'anodize' => 'Anodize',
        'number_of_anodize' => 'Jumlah anodize@',
        'P' => 'P',
        'L' => 'L',
        'elbow_type@' => '@siku',
        'screw_type@' => '@screw'
    ]
];
