<?php
return [
    'breakdown_col' => [
        'cat',
        'type',
        'kode',
        'Tpk',
        'No',
        'nama_modul',
        'component',
        'proses_khusus',
        'P',
        'L',
        'T',
        'ukuran',
        'Sub',
        'jml',
        'bahan',
        't_bahan',
        'l_bahan',
        'd_bahan',
        'luar',
        't_luar',
        'dalam',
        't_dalam',
        'P1',
        'P2',
        'L1',
        'L2',
        'p1_bahan',
        'p2_bahan',
        'l1_bahan',
        'l2_bahan',
        'profil3',
        'profil2',
        'profil',
        'siku_joint',
        'screw_jf',
        'door_mec',
        'rel',
        'engsel',
        'V',
        'V2',
        'H',
        'nama_barang',
        'panjang',
        'jumlah',
        'v_lap',
        'v_edg',
        'deskripsi_lapisan',
        'deskripsi_edging',
        'deskripsi_komponen',
        'nama_komponen',
        'minifix',
        'dowel',
        '@siku',
        '@screw',
        'dormec',
        'engsel*',
        'rel*',
        'p*',
        'l*',
        '2(p+l)',
        '(pxl)',
        'bahan_dasar',
        'deskripsi_bahan',
        '/panel',
        'jumlah_anodize@',
        'minifix@',
        'dowel@',
        'jml_siku',
        'jml_screw',
        'M2',
        'M3',
        'T_P1',
        'T_P2',
        'T_L1',
        'T_L2',
        'P_cnc',
        'L_cnc',
        'ukuran_cnc',
        'csv_format',
    ],

    'fields_mapping' => [
        'cat' => 'cat',
        'code' => 'type',
        'ks' => 'kode',
        'tpk' => 'Tpk',
        'no' => 'No',
        'nama_modul' => 'nama_modul',
        'component' => 'component',
        'proses_khusus' => 'proses_khusus',
        'P' => 'P',
        'L' => 'L',
        'T' => 'T',
        'ukuran' => 'ukuran',
        'number_of_sub' => 'Sub',
        'jml' => 'jml',
        'bhn' => 'bahan',
        't_bahan' => 't_bahan',
        'l_bahan' => 'l_bahan',
        'd_bahan' => 'd_bahan',
        'luar' => 'luar',
        't_luar' => 't_luar',
        'dalam' => 'dalam',
        't_dalam' => 't_dalam',
        'P1' => 'P1',
        'P2' => 'P2',
        'L1' => 'L1',
        'L2' => 'L2',
        'p1_bahan' => 'p1_bahan',
        'p2_bahan' => 'p2_bahan',
        'l1_bahan' => 'l1_bahan',
        'l2_bahan' => 'l2_bahan',
        'profil3' => 'profil3',
        'profil2' => 'profil2',
        'profil' => 'profil',
        'siku_joint' => 'siku_joint',
        'screw_jf' =>  'screw_jf',
        'door_mec' => 'door_mec',
        'rel' => 'rel',
        'engsel' => 'engsel',
        'V' => 'V',
        'V2' => 'V2',
        'H' => 'H',
        'nama_barang' => 'nama_barang',
        'panjang' => 'panjang',
        'jumlah' => 'jumlah',
        'v_lap' => 'v_lap',
        'v_edg' => 'v_edg',
        'deskripsi_lapisan' => 'deskripsi_lapisan',
        'deskripsi_edging' => 'deskripsi_edging',
        'deskripsi_komponen' => 'deskripsi_komponen',
        'nama_komponen' => 'nama_komponen',
        'minifix' => 'minifix',
        'dowel' => 'dowel',
        '@siku' => '@siku',
        '@screw' => '@screw',
        'dormec' =>  'dormec',
        'engsel*' => 'engsel*',
        'rel*' => 'rel*',
        'P*' =>  'p*',
        'l*' => 'l*',
        '2(p+l)' => '2(p+l)',
        '(pxl)' => '(pxl)',
        'bahan_dasar' => 'bahan_dasar',
        'deskripsi_bahan' => 'deskripsi_bahan',
        '/panel' => '/panel',
        'jumlah_anodize@' => 'jumlah_anodize@',
        'minifix@' => 'minifix@',
        'dowel@' => 'dowel@',
        'jml_siku' => 'jml_siku',
        'jml_screw' => 'jml_screw',
        'M2' => 'M2',
        'M3' => 'M3',
        'T_P1' => 'T_P1',
        'T_P2' => 'T_P2',
        'T_L1' => 'T_L1',
        'T_L2' => 'T_L2',
        'P_cnc' =>  'P_cnc',
        'L_cnc' =>  'L_cnc',
        'ukuran_cnc' => 'ukuran_cnc',
        'csv_format' => 'csv_format',
    ],

    'data_validation_col' => [
        'cat',
        'code',
        'name',
        'val',
        'ks',
        'ket',
        'jml sub',
        'bhn',
        'T',
        'minifix',
        'dowel',
        'tipe siku',
        'tipe screw',
        'V',
        'V2',
        'H',
        'profil3',
        'profil2',
        'profil',
        'L',
        'D',
        'P1',
        'P2',
        'L1',
        'L2',
        'Rel',
        'Engsel',
        'Anodize',
        'Jumlah anodize@',
        'P',
        'L*',
        '@siku',
        '@screw'
    ],

    'data_val_map' => [
        'cat' => 'cat',
        'code' => 'code',
        'name' => 'name',
        'val' => 'val',
        'ks' => 'ks',
        'Ket' => 'ket',
        'jml sub' => 'jml sub',
        'bhn' => 'bhn',
        'T' => 'T',
        'minifix' => 'minifix',
        'dowel' => 'dowel',
        'tipe siku' => 'tipe siku',
        'tipe screw' => 'tipe screw',
        'V' => 'V',
        'V2' => 'V2',
        'H' => 'H',
        'profil3' => 'profil3',
        'profil2' => 'profil2',
        'profil' => 'profil',
        'L' => 'L',
        'D' => 'D',
        'P1' => 'P1',
        'P2' => 'P2',
        'L1' => 'L1',
        'L2' => 'L2',
        'Rel' => 'Rel',
        'Engsel' => 'Engsel',
        'Anodize' => 'Anodize',
        'jumlah_anodize@' => 'jumlah_anodize@',
        'P' => 'P',
        'L*' => 'L*',
        '@siku' => '@siku',
        '@screw' => '@screw',
    ],

    'materials_col' => [
        'KATEGORI',
        'ID BARANG',
        'NAMA BARANG',
        'JML',
        'SATUAN',
        'KETERANGAN'
    ],

    'materials_map' => [
        'cat' => 'KATEGORI',
        'id' => 'ID BARANG',
        'name' => 'NAMA BARANG',
        'qty' => 'JML',
        'unit' => 'SATUAN',
        'note' =>  'KETERANGAN'
    ]
];
